version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile  # Use o Dockerfile personalizado
      target: api
    platform: linux/amd64  # Especifique a arquitetura da imagem
    ports:
      - "8000:8000"
    environment:
      - MONGO_URI=mongodb+srv://guilhermeaugustosfc1:aIVlKXsQV0FNC3Pu@cluster0.yiwrufx.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0&tlsAllowInvalidCertificates=true
      - PYTHONPATH=${PYTHONPATH}:/repository:/database:/model
    networks:
      - myfintechnetwork

networks:
  myfintechnetwork:
    driver: bridge
